README.md

This adds a quick citation/link to TrueBrain's OpenTTD Savegame Reader. TrueBrain is listed as a contributor, even though they haven't (and probably won't) directly contribute to this project. So it's a "thank you", but also hints at "unaffiliated with".

docs: cite upstream fork

---

README.md

I think it's clearer to avoid the very GitHub specific language

docs: use based on rather than forked

---

README.md

This uses GitHub's "alert" syntax for highlighting the fact that the README is more of a spec.
This is to draw attention to it a bit better (and maybe to experiment with the syntax a bit + deliberatly try to be more familiar with it). Not sure exactly which level should be used - but avoiding the stronger levels to already start from the point of avoiding their overuse

docs: use Note alert to highlight WIP

---

README.md

This is to make it so the variable is hopefully clearer...
... although we now have get_config, load_config, and save_config. Hmmm...

docs: rename variables so they're shorter

---

README.md

Realise the name and mentioning of
https://github.com/TrueBrain/OpenTTD-savegame-reader might hint that it is. It's probably good form to make it really clear that it's not.

docs: mention that this project is not affiliated with OpenTTD

---

pyproject.toml

This adds support from 3.6.7. While Python 3.6 is quite old now, want to have as high support as possible to make this as useful as possible so people that can't upgrade for whatever reason can still use this.
3.6.7 is chosen because I know that GitHub actions can run tests on it without too much faff, as in
https://github.com/uktrade/stream-zip/blob/main/.github/workflows/test.yml

feat: support Python from 3.6.7

---

requirements.base
requirements.txt

Removed for s reasons:
- Dependencies on now specified via pyproject.toml
- I think we also don't need the dependencies that they specify

chore: remove requirements files

---

.coveragerc
.github/workflows/test.yml
codecov.yml
pyproject.toml

A bit trivial for now, but start as we mean to go on...
This does make CI use the latest version of dependencies used for testing. This is because pytest would fail on Python 3.11.0 for some reason. Deeming it not worth finding out why

ci: test with code coverage

---

README.md

Partially just to follow the trends, but also (eventually) to evoke trust, and also to keep on a good path.

docs: add badges for PyPI, GitHub Actions and CodeCov

---

.github/workflows/test.yml
openttdlab.py
pyproject.toml

Only trying to support Linux and MacOS, because that's all I have access to at the moment.
These tests don't mock anything, and really do download OpenTTD. Maybe not ideal, but it's the easiest thing for now.
BREAKING CHANGE: This drops support for Python earlier than 3.8. This is because the latest version of platformdirs only support Python 3.8 onwards. Often I think using an earlier version is fine, but because it's involved in saving files to the user's machine, I'm opting to just use the most recent out of paranoia.
This should also mean we can now pin the dev dependencies in CI - they were unpinned to allow different versions to run earlier versions of Python.

feat!: download OpenTTD to a cache directory

---

README.md

This should avoid issues with pip/python are installed in different locations

docs: use python rather than pip

---

.github/workflows/test.yml
README.md
openttdlab.py

This extracts the OpenTTD binary (+ any assocaited files) from the downloaded archive. The 7-zip binary is used for this. While a bit awkward, it does extract dmg files on macOS, and without any sort of mounting of it.

feat: extract the downloaded file

---

README.md

In one place it's get_config, and in another get_experimental config. This change makes it consistent.

docs: use get_config consistently

---

README.md

This makes the image height in the document the same as the SVG

docs: tweak height of logo

---

README.md

A bit of brief testing in VoiceOver describes each of these as "unlabelled image", even though the internal SVG has what I thought was the right attributes to be read. Putting alts back onto the images so hopefully they are just a touch more accessible.

docs: add image alt

---

README.md

This is to try to make the logo show up when published to PyPI - so far it doesn't.

docs: use raw url for logo rather than relative link

---

README.md

Suspect it's not helpful, and maybe even defensive. Maybe down the line can have something a bit better

docs: remove API design considerations

---

.github/workflows/deploy-package-to-pypi.yml
openttdlab.py

This is fairly standard these days, and will allow OpenTTD to output and save its own version

feat: include version in source file

---

.github/workflows/deploy-package-to-pypi.yml

This hopefully fixes how the git tag is replaced in files - it's erroring how because I think it's assuming all the lines in the run block are a single command.

fix: deploying to PyPI

---

.gitignore

This takes the .gitignore file from https://github.com/github/gitignore/blob/main/Python.gitignore. This file is is subject to CC0, which is GPL compatible: https://github.com/github/gitignore/blob/main/LICENSE
This is done to try to make sure as few files appear in git status when developing that don't need to be committed.

devex: more recent Python .gitignore

---

openttdlab.py

This changes OpenTTD -> OpenTTDLab, because this is OpenTTDLab, not OpenTTD.

docs: fix typo/copy-paste error in notice

---

openttdlab.py

For me, it's clearer in some cases to have the comments on the same line as the code. e.g. when the lines are short as in the case here of passing command line arguments to the OpenTTD binary.

style: comments on same line as code

---

openttdlab.py

This moves the imports to the top of the Python file, because it's more usual to have them there.

refactor: tidy imports

---

README.md
openttdlab.py

Suspect it's more appropriate than the GitHub ID

docs: use the real name of savegame-reader's author

---

README.md

It's not needed as far as I can tell, license-wise, and seems borderline defensive.

docs: remove non-affiliation-statement

---

README.md

Don't think it's required to do this in the README (it is mentioned in the file itself), but I think it's nice to have them listed.

docs: make the original author of the logo clear

---

openttdlab.py
test_openttdlab.py

The tests seem to be slightly flakey on the number of saved files. Hopefully disabling threaded saves addresses this.

fix: more deterministic saving

---

.github/workflows/test.yml
openttdlab.py

This tests on macOS, and reduces the number of Python versions tested just to try to make sure I don't run out of GitHub actions minutes.

ci: test on macOS (and fewer Python versions)

---

openttdlab.py

This should then allow other ways of copying files to the target location, e.g. http

refactor: delegate copying of ai file to function

---

README.md

This is because technically, the text of the GPL v2 is _not_ released under GPL v2. Could add that detail in, but suspect it's not helpful. No-one probably cares and it's clear enough to state that OpenTTDLab is GPL v2.

docs: remove detail about every file being GPL v2

---

openttdlab.py

Now only once per run_experiment call
(Suspect could do with figuring out how to cache them...)

perf: less downloading of AIs

---

README.md
openttdlab.py
test_openttdlab.py

I might change my mind on this, but it might make certain things easier. Say to measure total wallclock time compared with number of processes, or total memory used with number of processes.

feat: return a (so far null) metadata for cpu and memory info

---

openttdlab.py
test_openttdlab.py

This gives a slightly rough way to set any config value for the experiment. It also tests 3 savegame compression formats that are common.

feat: a rough way of settings any config value

---

README.md
openttdlab.py
test_openttdlab.py

There are a few steps involved here. Hopefully it's as simple as it can reasonably be.
The client code does take both a name and unique ID of the AI. Ideally we would just take name so it's clear to the user which AI is being used. However, names are not unique, so to disambiguate them just in case there are multiple AIs with the same name, it also requires the unique ID

feat: ability to fetch AIs published on content server

---

README.md

I think OpenTTDLab makes more sense here

docs: change reference from OpenTTD to OpenTTDLab

---

README.md

I suspect it's not helpful to have - it's a very big list of nested dicts

docs: remove printing of results from experiment

---

openttdlab.py
test_openttdlab.py

This starts the AIs in the game immediately using a startup script, rather than waiting for them to be launched by the game engine.
Although not quite possible here yet, this is a step towards passing parameters to AIs, which would be useful when using OpenTTDLab to choose appropriate default parameters for them.
---
**BREAKING CHANGE**: Changes the results from experiments
This changes the results of OpenTTDLab because the AIs start at a different point in time than they did before. But hopefully this is a better choice - they start immediately.

feat: start AIs immediately using a startup script

---

README.md
examples/01-single-ai.ipynb
examples/02-openttdlab-scaling.ipynb
openttdlab.py
test_openttdlab.py

This allows the passing of parameters to AIs.
BREAKING CHANGE: this changes how the `ais` parameter is used. Each item was a pair, but now it's a triple.

feat: allow passing of parameters to AIs

---

README.md
examples/01-single-ai.ipynb
examples/02-openttdlab-scaling.ipynb
openttdlab.py
test_openttdlab.py

This makes it slightly easier to pass AIs to the API - no nested tuples, and no requirements for an empty parameter list for example.
BREAKING CHANGE: How AIs were passed to the run_experiment function has changed.
It was an iterable of tuples, but now an iterable of the return values of the 4 AI-fetcher functions.

feat: slightly less clunky API for AIs

---

README.md
openttdlab.py
test_openttdlab.py

BREAKING CHANGE: The function bananas_file is renamed to bananas_ai
This is to make way for other bananas_* functions, and specifically thinking of bananas_ai_library to be able to use published libraries (specifically for pathfinding)

feat: rename bananas_file to bananas_ai

---

README.md
openttdlab.py

This adds the option to take a screenshot at the end of each simulation, by the `final_screenshot_directory` option to `run_experiment`.
How it works is that it loads OpenTTD again at the end of each simulation, but with the normal video driver, loading the final autosave file, takes a screenshot, and then exits. This can result in the OpenTTD window being visible for a few moments for each run, This seems unavoidable at the moment - it doesn't seem possible to take screenshots using the null video driver.

feat: option to take final screenshot

---

README.md
test_openttdlab.py

OpenTTDLab won't currently work with what is now the latest version OpenTTD, OpenTTD 14.0.
Hopefully there is some way to make it work, but for now, just disabinge the test that uses the latest versions and put notes in the README.
Some related discussion at https://github.com/OpenTTD/OpenTTD/discussions/12496

tests: disable test that uses the latest version of OpenTTD

---

README.md
openttdlab.py
test_openttdlab.py

I think it seems more natural that a single "experiment" is essentially a single run of OpenTTD, and a call to this function runs a lot of them.
This I think this will work especially with a future change that will have `experiments` as a single parameters that controlls all of these experiments.
BREAKING CHANGE: This renames run_experiment to run_experiments

feat!: rename run_experiment to run_experiments

---

README.md

Doing this was missed in previous releases - this brings the README up to date with the code.

docs: document experiments parameter

---

README.md
openttdlab.py
test_openttdlab.py

This allows, for example, a single call to run_experiments to cover multiple terrain types, which are set via config
It also removes the "base" detail from the name. It was chosen to emphasise that under the hood, OpenTDDLab adds to it, but I think this detail isn't really needed to be emphasised - it adds to the load of what you have to think about somewhat needlessly.

feat: allow OpenTTD config to be changed per experiment

---

README.md
openttdlab.py
test_openttdlab.py

From running experiments with many runs, memory usage would get higher and higher and higher, eventually causing Python to get killed because it would use loads of memory (e.g. I have seen it use 30GB). Suspecting that keeping all the parsed save games in memory is a contributing factor - usually only want to keep a very small amount of data, especially when running for a long time I know what data I want to extract because I've run smaller "pilot" experiments.
This change adds an intermediate "result processor" that means that, hopefully, only what's needed is stored.
Also, am suspecting that parsing the savegame which is done in Python is making the scaling not great due to Python's GIL. If we move to a multi-processing solution that could address that, but also would be good to have a …

feat: add result processor

---

README.md
openttdlab.py
test_openttdlab.py

This changes how the result processor works - it now returns an iterable of rows that will be returned in the final results set.
This means it can return a result row per player for example, which adds a bit of flexibility and I think makes it possible to return results that are more (Hadley Wickham) tidy.

feat: make the result processor return iterable

---

openttdlab.py

This change renames variables from having just "name" in their name, to "filename" in their names, because they do represent filenames in the filesystem.

refactor: clearer variable names

---

openttdlab.py
test_openttdlab.py

If an AI (or AI library) that is downloaded from BaNaNaS itself requires (other) AI Libraries, these are automatically downloaded, including transitive dependencies

feat: automatically download dependencies from BaNaNaS

---

openttdlab.py
test_openttdlab.py

This adds "output" to each result row, which was the combined text stdout and stderr output for that run of OpenTTD - if there is no error this is usually empty.
It also adds an "error" key which indicates if a script errored during that run, and exited, which means it can be excluded from results/investigated further as appropriate.

feat: output combined stdout and stderr, and indicate if we think it errored

---

README.md

GitHub doesn't seem to be able to show its fancy note/warning syntax in lists, so going for a simpler view.

docs: fix style around version warning

---

openttdlab.py
test_openttdlab.py

For some reason in older releases of OpenTTD, when uncompressing the dmg files to where there were already files, it would result in "Operation not permitted" errors (and only on the second run or beyond).
To solve this, uncompressing the files into the run directory, which gets cleared up automatically at the end anyway.
This also means the cache directory is left tidier, with no ucompressed files, which I don't think is bad thing.

feat: uncompress binaries into the run directory rather than the cache directory

---

openttdlab.py
pyproject.toml

Doing some very light nosing around `top` when experiments are running, often there are fewer openttd processing running than expected, and Python is 100%. So I suspect that Python is parsing the savegame files, and the GIL stops good scaling.
So, moving to using processes instead of threads for the parsing component.
Also, using the multiprocess module, with dill, rather than Python's built in multiprocessing, because it allows more things to be transferred to and from the process (e.g. lambda and local functions).

feat: move to multiprocess from threads

---

openttdlab.py
pyproject.toml

Although there is a touch more awkwardness in communicating with the subprocess, pytest-cov handles code coverage in the subprocess's function. Couldn't get coverage working at all with the 3rd party multiprocess module.
For now still using "dill" to pass data back and forth since lambda functions can be passed without too much fuss.

feat: use built-in Python multiprocessing

---

openttdlab.py

Instead, it should go into the run directory along with the OpenTTD binary

fix: don't copy the OpenGFX binary to the current directory

---

openttdlab.py
test_openttdlab.py

This fixes 'No such file or directory' errors when attempting to use AI libraries that have been already cached.
(This might need a manual clear of the cache directory if you have previously cached libraries)

fix: caching behaviour of libraries when there are multiple

---

README.md

Think it's clearer because "fetching" isn't always involved

docs: rename fetching to configuring

---

README.md

Not great to have 2 sections named the same thing.

docs: rename second 'Running experiments' section to 'Core function'

---

openttdlab.py

If making a public function for downloading want to give it as few arguments as possible I think

refactor: remove almost unused argument in (private) _bananas_download

---

openttdlab.py

Maybe down the road can have a nicer format of the cache to allow caches from older versions to be used in new, but for now I think not worth it.

feat: bust cache between versions of OpenTTDLab

---

README.md
openttdlab.py
test_openttdlab.py

Although the aim isn't exactly to have a BaNaNaS client, having it public forces clearer API, which I think will help on reporting on exact versions later, so may as well

feat: public BaNaNaS client

---

README.md
openttdlab.py
test_openttdlab.py

This change allows client code to fetch the exact version of content from BaNaNaS, if the full MD5 is supplied.
This change also now returns the full MD5 of content downloaded, but only for content that has been distributed with a license that I think allows download of the version in perpetuity. This covers virtually all current content on BaNaNaS. The only content in BaNaNaS right now where this doesn't is one with a "Custom" license.

feat: allow download of exact version from BaNaNaS

---

README.md
openttdlab.py

This combines openttd_base_url and opengfx_base_url into a single parameter, openttd_cdn_url, which now should not include the path/folder component.
This is a stepping stone to being able to easily use nightly versions of OpenTTD. To specify their location another parameter could have been introduced, but I'm not sure of the use case. Keeping it simple, opting to just have the one parameter that specifies the location of the OpenTTD CDN as a "just in case"/"let's keep it flexible/configurable" parameter.

feat!: simplify configuration of where to fetch OpenTTD binaries from

---

openttdlab.py

It was a bit of an odd oversight to both hardocde ("content.openttd.org", 3978) twice and to pass the first instance about as though to use it. Opting to just hard code it once.

refactor: use argument passed to function

---

README.md
openttdlab.py
test_openttdlab.py

This includes removing the sha256 of each of the binary file archives from the location of the binary files inside the "run" directory.
This is to avoid the error on Windows:
> FileNotFoundError: [WinError 206] The filename or extension is too long
The "run" directory is already a temporary directory with at least one unique ID, and we already have checked the sha256 of the file contents by this point, so having the sha256 of the binary archive in the path doesn't give anything.
Note that although this supports _some_ nightlies from a downloading and running OpenTTD point of view, the version of OpenTTD must still be compatible with OpenTTDLab in terms of extracting data, and not all version of OpenTTD are compatible.

feat: support some OpenTTD and OpenGFX nightlies

---

README.md
docs/assets/openttdlab-logo.svg
paper/paper.md

Have to admit I'm not 100% if such a conversion adds to the people who own copyright.

docs: include person who converted OpenTTD logo to SVG as author

---

paper/paper.md

docs: use predecessors rather than forebears

---

README.md
openttdlab.py
test_openttdlab.py

This fixes https://github.com/michalc/OpenTTDLab/issues/234 by using the "schedule" console script command, added in https://github.com/OpenTTD/OpenTTD/pull/12761 and released in OpenTTD 15, to emulate the pre OpenTTD 14 in-game-time autosave behaviour.
This also adds in a savegame just after the AI creation, which I think is probably a good thing in terms of charting results

feat: support OpenTTD 15

---

CITATION.cff
README.md

Hard to know the right thing, but
- https://ror.org/01nrxwf90 does not include 'The' in the institution name (but it does for other institution names)
- https://www.wikidata.org/wiki/Q160302 has 'The University of Edinburgh' only in the "Also known as" section
- https://api.crossref.org/funders/501100000848 also 'The University of Edinburgh' only in the 'alt-names' section
What this is _not_ consistent with is that https://www.ed.ac.uk/ seemingly everywhere uses 'The/the University of Edinburgh'.

docs: ensure no 'The' when referring to the Unversity of Edinburgh in a citation

---

.github/workflows/test.yml
README.md
pyproject.toml

The previous version of Ubuntu has been retired from GitHub actions, and the more recent versions don't have support for older Python. To run older Python, it seems the easiest way is to install it with uv. But uv also doesn't seem to support Python 3.8.0 and Python 3.8.1. Suspect it's not worth putting too much effort into supporting these two specific versions, so dropping support for them.

feat: drop support for Python 3.8.0 and 3.8.1
