README.md
This is in case anyone stumbles on this while it doesn't actually work
=> docs: mention that this is a WIP and the README is a design spec

pyproject.toml
This adds a single Python module as documented in the WIP README
For now, I'm going to go for a single file approach as in some of my other projects. See how far that can go.
=> feat: initial empty openttdlab module

README.md
This means config for experiments can be shared
=> docs: include suggestion on how to save and load the file

README.md
Just to make it clear it's choice. Might change if it has some benefits down the line.
=> docs: mention that we're OOP-free mostly for now

.github/workflows/test.yml, openttdlab.py, pyproject.toml, test_openttdlab.py
This adds initial, empty, functions, and the starts of tests (and CI) to test them.
=> feat: initial empty functions

openttdlab.py, test_openttdlab.py
This sets up empty skeleton functions to run the experiment and to get config
=> feat: initial run_experiment and get_config functions

README.md, docs/assets/openttdlab-logo.svg
Very rough attempt at a logo based on the OpenTTD logo.
The OpenTTD logo was taken from
https://commons.wikimedia.org/wiki/File:Openttdlogo.svg and modified. This should be fine because it's GPL-2.0, as is this project.
=> docs: first attempt at logo

README.md
Need to think about this some more, but in terms of the sort of reproducible-ness, not sure if it's really one of the things to be concerned about...
=> docs: remove granularity of output from experiment description

README.md
Which for example mention tar and unzip
=> docs: clearer installation instructions

openttdlab.py, test_openttdlab.py
A very small step towards actually extracting something of value - returning the binary contents of a single savegame file
=> feat: extract (very unusable) results

README.md
It feels just a bit overcomplex to have to setup an experiment. It's not exactly easy! I think it should "just work", with the ability to more sort of "formally" reproduce if needed..
=> docs: simpler 1-stage API

openttdlab.py, test_openttdlab.py
It is feeling much better - far less faffy somehow.
=> feat: implement some of the simpler one stage API

.flake8
Not using flake8, so removing its config file
=> refactor: remove unused file

README.md
This is for clarity, but also just trying to be nice.
=> docs: add licenses and attributions section

README.md
Think less is more here - hopefully down the line could have screenshots and maybe a video?
=> docs: much more concise introduction

openttdlab.py, test_openttdlab.py
=> feat: parse just a single save game, asserting can extract the AI name

README.md, openttdlab.py, test_openttdlab.py
Very rough - much tweaking will be needed
=> feat: allow days to run to be configurable and return results for each save file

openttdlab.py
This is so it gets cleaned up at the end
=> feat: run experiment into a temporary directory

openttdlab.py, test_openttdlab.py
=> feat: extract a much smaller subset of data

README.md, openttdlab.py, test_openttdlab.py
This is a small stepping stone to hopefully be able to download them from OpenTTD, e.g. from GitHub
=> feat: use a function to get AI files

openttdlab.py
This is a step towards a unified mechanism of reading bytes
=> refactor: make binary reader return length read

openttdlab.py, test_openttdlab.py
Fairly hefty refactor: less mutation, duplication and fewer classes
=> refactor: less mutation when reading items

README.md
Don't think it needs quite as much detail as I gave it
=> docs: shorter WIP warning

openttdlab.py
Or could also be described as using a more "guard"-style
=> refactor: reduce a small amount of nesting

openttdlab.py
Think I might just be restoring the vibe of the original comment that was here before I started cutting things down...
=> docs: more detail on why no supporting OTTD

openttdlab.py
And makes it a bit clearer that the headers and records are for the _table_ chunks and not the others.
=> refactor: fewer cases of if for flow control

README.md, openttdlab.py, test_openttdlab.py
This removes the metadata and config return value items from results. Maybe down the line they will make a comeback, but I suspect they might be overcomplicated even for reproducibility. I think the next steps will probably be to accept versions of OpenTTD, OpenGFX, and any AIs used. If then we want something more complex, can add it at that point.
=> feat: a more straightforward API

openttdlab.py
This adds the ability to run experiments in parallel, using the max_workers argument to run_experiment. The name of this arugument is chosen for consistency with the concurrent.futures Python standard library module.
It defaults to os.cpu_count(): OpenTTD I think is single threaded, and the settings I _think_ should take it to ~100% of a CPU. I suspect could do with some metrics to see what a good default really is.
This does use the ThreadPoolExecutor because for the most part the Python part doesn't do much - OpenTTD runs in a subprocess started from each of these threads. Parsing the saved games is maybe an exception, and probably won't be parallelised because of the GIL. However, I suspect it's a tiny fraction of overall runtime in most cases, and it's unlikely that each run of …
=> feat: run experiments in parallel

README.md
To try to make clear what the point of this is
=> docs: add list of features

README.md, openttdlab.py, test_openttdlab.py
This should make the results more reproducible.
=> feat: allow the specification of OpenTTD and OpenGFX version

openttdlab.py, test_openttdlab.py
In case the default (latest) version was used, at least which will be in the results to know for next time.
=> feat: include OpenTTD and OpenGFX version in results

openttdlab.py
This makes all HTTP requests auto retry the connection. It also makes the client configurable which gives more flexibility, including from tests down the line.
=> feat: retry HTTP requests, and make the client configurable

README.md, openttdlab.py, test_openttdlab.py
This should make it just a touch easier to run with AIs in development
=> feat: support an AI in a local folder

examples/01-single-ai.ipynb, examples/02-openttdlab-scaling.ipynb
Suspect that the AIs parameter doesn't match the version
=> docs: fix the OpenTTD version in the example notebooks

README.md
Previously the arguments were in the incorrect order. This PR fixes that.
=> docs: Updating example code in README

openttdlab.py, pyproject.toml
It was getting a bit painful it just sitting there with no feedback, especially with high numbers of experiments.
At the moment it just advances when each experiment is complete. However, it could get fancy down the line and detect when save games have been output.
Rough screenshot of me using it in Jupyter Lab:
=> feat: show basic progress bar when running

openttdlab.py
An 'experiment' is more consistently single execution of OpenTTD, with a seed and some other configuration. This change makes the variable names in the code more consistent with that labelling.
This supports later changes to allow the `run_experiments` function to run a wider range of experiments.
=> refactor: swap 'experiment' and 'run' in variable names

README.md, openttdlab.py, test_openttdlab.py
So the experiments can be distinguished in results, the details of each need to be returned.
=> feat: expose experiment dictionary in results

openttdlab.py
In a later change will be using more of the bytes from the BaNaNaS response, and specifically those to find (and then download) the dependencies of an AI
=> refactor: read all bytes from socket when querying BaNaNaS

openttdlab.py
To do this the download function is going to have to return some sort of list of everything that an AI needs, in order to then be copied into the run directory.
So returning just the one thing the download function is downloading, and then using it, is a small step towards this.
=> refactor: step towards automatically downloading dependencies

openttdlab.py
This makes the downloading and caching code use the information gained from downloading, which is a bit closer to what it would need to be when we automatically download dependencies for AIs - we won't have information from client code.
=> refactor: store files using info from downloading

openttdlab.py
This is a stepping stone to the downloading of an AI from BaNaNaS automatically downloading the dependencies needed - more of the code converted to lists of filename rather than just a single filename.
=> refactor: more code that support multiple files per AI

openttdlab.py
Makes more of the code independent of the difference between AIs and their libraries, as stepping stones towards downloading AI libraries when downloading AIs.
=> refactor: towards downloading AI libraries from AI download

openttdlab.py
When fetching dependencies (especially recursively) we'll be repeatedly querying the TCP server for dependencies, so it makes sense to have it in a function.
=> refactor: move fetching content ID to function

fixtures/NoOpAIImportingPathfinder-1/info.nut, fixtures/NoOpAIImportingPathfinder-1/main.nut, openttdlab.py, test_openttdlab.py
I suspect that OpenTTD needs files in folder in the tar file
=> fix: local folder behaviour

README.md
It might be helpful if people want to explore savegame files generated separately
=> docs: documentation on parse_savegame

openttdlab.py
Having a public BaNaNaS client isn't exactly a main aim of OpenTTDLab, but I suspect it'll push me to make it clearer and more robust, so should indirectly help
=> refactor: use partial to reduce indentation and step towards public BaNaNaS client

openttdlab.py
A small stepping stone to a nicer bananas download function
=> refactor: fewer arguments in private bananas function

openttdlab.py
Another stepping stone to a public bananas download function
=> refactor: fewer arguments private bananas download function

openttdlab.py
Both to for clarity reasons, to show we don't need to download when we connect to the TCP server, but also suspect this is a stepping stone to a nicer API for the bananas download function (that I suspect will not write to "target" files but instead offer iterables of data), and also will make at most one TCP connection.
=> refactor: split querying TCP server and download

README.md
The TOC I think is right - was confused in an earlier tidy up
=> docs: fix titles to match TOC

openttdlab.py
The AI and AI library funcs now return iterables of data, and specifically the _bananas_download function does this (rather than writing to a target file).
This is a step towards a nicer API for it ready to make it public. And, hopefully, be able to expose more data for reproducible experiments, so the exact same version from bananas is used again later.
=> refactor: AI and AI library funcs return iterables of data

openttdlab.py
This is a small step to it being more public (since it probably will expose a way of customising the http client).
=> feat: use context in bananas download function for http client

openttdlab.py
A step towards an easier to use separate function
=> feat: bananas http client has default

README.md, openttdlab.py, test_openttdlab.py
This is a stepping stone to allowing download of the exact version of content to be downloaded, if we're fairly sure that the license allows it.
=> feat: expose the license when downloading from BaNaNaS

README.md
Feels a bit odd to use "I" here.
=> docs: tweak cite language

README.md
To make this hopefully slightly clearer what this is
=> docs: add about section

README.md
To make it clearer what it is, hopefully
=> docs: links to trAIns

README.md
This is to it make it very clear how to contribute, get support, or raise an issue, which are requirements for JOSS.
=> docs: add contributing, support, and issues sections

paper/paper.bib
Suspect they are read by the JOSS editorialbot
=> docs: add DOIs to paper

CITATION.cff
Basing on
https://github.com/citation-file-format/ruby-cff/blob/8f4e37e12b8511a4b93991abaf7e6c0233c48939/test/files/formatter/preferred-citation-masters-thesis.cff
=> docs: improve CFF file for master's dissertation
